version: '3.8'

services:
  # 1. 백엔드 컨테이너 설정
  powiki-back:
    # 도커 허브 창고에서 가져올 이미지 이름
    image: ${DOCKER_USERNAME}/powiki-back:latest
    container_name: powiki-back
    ports:
      - "8080:8080"  # [외부포트]:[컨테이너내부포트]
    restart: always  # 서버가 꺼졌다 켜지면 자동으로 다시 실행

  # 2. 프론트엔드 컨테이너 설정
  powiki-front:
    image: ${DOCKER_USERNAME}/powiki-front:latest
    container_name: powiki-front
    ports:
      - "80:80"      # 사용자가 80번(HTTP)으로 들어오면 연결$
    restart: always
    depends_on:
      - powiki-back  # 백엔드가 먼저 실행된 후 프론트가 실행되도록 설정