server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 핵심: 경로를 못 찾으면 index.html로 보내서 리액트 라우터가 처리하게 함
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 포트 숨기기
    location /api/ {
        proxy_pass http://168.107.13.225:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}