spring.application.name=powiki
spring.profiles.include=local

# ?????? ??
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${db.url}
spring.datasource.username=${db.id}
spring.datasource.password=${db.password}

# myBatis ??
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.example.powiki
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true

# ?? ??
logging.level.com.example.powiki=DEBUG

# ????? ?? ?? ?? ??
cors.allowed-host=http://localhost
cors.allowed-port=5173

